// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }


const moo = require("moo");
const lexer = moo.compile({
    _LIM: /\blim\b/,
    _TO: /->/,
    _OF: /\bof\b/,
    _USE: /\buse\b/,
    IDENTIFIER: /(?!\b(?:inf|of|use|lim|Any|Infinite|Nexists|Number|Tensor|Undefined|Variable)\b)[A-Za-zº$%]+/,
    OBJECT: /\@(?:Any|Infinite|Nexists|Number|Tensor|Undefined|Variable)\b/,
    _INF: /\binf\b/,
    _EXPONENTIATION: /\^/,
    NUMBER: /[0-9]+/,
    _DOT: /\./,
    _BINDING: /==/,
    _EQUALITY: /=/,
    OPERATOR: /[\*\/]/,
    SIGNS: /[+-]+(?:\s*[+-]+)*/,
    SIGN: /[+-]/,
    _OPEN: /\(/,
    _CLOSE: /\)/,
    _ENTER: /\[/,
    _COMMA: /,/,
    _EXIT: /\]/,
    _S: / +/,
    _L: {match: /\n/, lineBreaks: true},
    QUOTE: /#(?: [^\n]*)?/
});

var grammar = {
    Lexer: lexer,
    ParserRules: [
    {"name": "start$ebnf$1", "symbols": []},
    {"name": "start$ebnf$1$subexpression$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)]},
    {"name": "start$ebnf$1$subexpression$1", "symbols": [(lexer.has("_L") ? {type: "_L"} : _L)]},
    {"name": "start$ebnf$1", "symbols": ["start$ebnf$1", "start$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "start$ebnf$2$subexpression$1$ebnf$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "start$ebnf$2$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "start$ebnf$2$subexpression$1$ebnf$2", "symbols": []},
    {"name": "start$ebnf$2$subexpression$1$ebnf$2$subexpression$1$ebnf$1", "symbols": [(lexer.has("_L") ? {type: "_L"} : _L)]},
    {"name": "start$ebnf$2$subexpression$1$ebnf$2$subexpression$1$ebnf$1", "symbols": ["start$ebnf$2$subexpression$1$ebnf$2$subexpression$1$ebnf$1", (lexer.has("_L") ? {type: "_L"} : _L)], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "start$ebnf$2$subexpression$1$ebnf$2$subexpression$1$ebnf$2", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "start$ebnf$2$subexpression$1$ebnf$2$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "start$ebnf$2$subexpression$1$ebnf$2$subexpression$1", "symbols": ["start$ebnf$2$subexpression$1$ebnf$2$subexpression$1$ebnf$1", "level1", "start$ebnf$2$subexpression$1$ebnf$2$subexpression$1$ebnf$2"]},
    {"name": "start$ebnf$2$subexpression$1$ebnf$2", "symbols": ["start$ebnf$2$subexpression$1$ebnf$2", "start$ebnf$2$subexpression$1$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "start$ebnf$2$subexpression$1", "symbols": ["level1", "start$ebnf$2$subexpression$1$ebnf$1", "start$ebnf$2$subexpression$1$ebnf$2"]},
    {"name": "start$ebnf$2", "symbols": ["start$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "start$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "start$ebnf$3", "symbols": []},
    {"name": "start$ebnf$3$subexpression$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)]},
    {"name": "start$ebnf$3$subexpression$1", "symbols": [(lexer.has("_L") ? {type: "_L"} : _L)]},
    {"name": "start$ebnf$3", "symbols": ["start$ebnf$3", "start$ebnf$3$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "start", "symbols": ["start$ebnf$1", "start$ebnf$2", "start$ebnf$3"]},
    {"name": "declaration$ebnf$1$subexpression$1", "symbols": [(lexer.has("OBJECT") ? {type: "OBJECT"} : OBJECT), (lexer.has("_S") ? {type: "_S"} : _S)]},
    {"name": "declaration$ebnf$1", "symbols": ["declaration$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "declaration$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "declaration$ebnf$2", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "declaration$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "declaration$ebnf$3", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "declaration$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "declaration", "symbols": ["declaration$ebnf$1", "variable", "declaration$ebnf$2", (lexer.has("_EQUALITY") ? {type: "_EQUALITY"} : _EQUALITY), "declaration$ebnf$3", "expression"]},
    {"name": "definition$ebnf$1$subexpression$1", "symbols": [(lexer.has("OBJECT") ? {type: "OBJECT"} : OBJECT), (lexer.has("_S") ? {type: "_S"} : _S)]},
    {"name": "definition$ebnf$1", "symbols": ["definition$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "definition$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "definition$ebnf$2", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "definition$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "definition$ebnf$3", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "definition$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "definition", "symbols": ["definition$ebnf$1", "variable", "definition$ebnf$2", (lexer.has("_BINDING") ? {type: "_BINDING"} : _BINDING), "definition$ebnf$3", "expression"]},
    {"name": "annotation$ebnf$1", "symbols": []},
    {"name": "annotation$ebnf$1$subexpression$1$ebnf$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "annotation$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "annotation$ebnf$1$subexpression$1$ebnf$2", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "annotation$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "annotation$ebnf$1$subexpression$1", "symbols": ["annotation$ebnf$1$subexpression$1$ebnf$1", (lexer.has("_COMMA") ? {type: "_COMMA"} : _COMMA), "annotation$ebnf$1$subexpression$1$ebnf$2", "variable"]},
    {"name": "annotation$ebnf$1", "symbols": ["annotation$ebnf$1", "annotation$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "annotation", "symbols": [(lexer.has("OBJECT") ? {type: "OBJECT"} : OBJECT), (lexer.has("_S") ? {type: "_S"} : _S), "variable", "annotation$ebnf$1"]},
    {"name": "node", "symbols": ["expression"]},
    {"name": "equation$ebnf$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "equation$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "equation$ebnf$2", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "equation$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "equation", "symbols": ["expression", "equation$ebnf$1", (lexer.has("_EQUALITY") ? {type: "_EQUALITY"} : _EQUALITY), "equation$ebnf$2", "expression"]},
    {"name": "comment", "symbols": [(lexer.has("QUOTE") ? {type: "QUOTE"} : QUOTE)]},
    {"name": "use", "symbols": [(lexer.has("_USE") ? {type: "_USE"} : _USE), (lexer.has("_S") ? {type: "_S"} : _S), (lexer.has("IDENTIFIER") ? {type: "IDENTIFIER"} : IDENTIFIER)]},
    {"name": "expression$ebnf$1$subexpression$1$ebnf$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "expression$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "expression$ebnf$1$subexpression$1", "symbols": [(lexer.has("SIGNS") ? {type: "SIGNS"} : SIGNS), "expression$ebnf$1$subexpression$1$ebnf$1"]},
    {"name": "expression$ebnf$1", "symbols": ["expression$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "expression$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "expression$ebnf$2", "symbols": []},
    {"name": "expression$ebnf$2$subexpression$1$ebnf$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "expression$ebnf$2$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "expression$ebnf$2$subexpression$1$ebnf$2", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "expression$ebnf$2$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "expression$ebnf$2$subexpression$1", "symbols": ["expression$ebnf$2$subexpression$1$ebnf$1", (lexer.has("SIGNS") ? {type: "SIGNS"} : SIGNS), "expression$ebnf$2$subexpression$1$ebnf$2", "level3"]},
    {"name": "expression$ebnf$2", "symbols": ["expression$ebnf$2", "expression$ebnf$2$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "expression", "symbols": ["expression$ebnf$1", "level3", "expression$ebnf$2"]},
    {"name": "term$ebnf$1", "symbols": []},
    {"name": "term$ebnf$1$subexpression$1$ebnf$1$subexpression$1$ebnf$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "term$ebnf$1$subexpression$1$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "term$ebnf$1$subexpression$1$ebnf$1$subexpression$1", "symbols": ["term$ebnf$1$subexpression$1$ebnf$1$subexpression$1$ebnf$1", (lexer.has("OPERATOR") ? {type: "OPERATOR"} : OPERATOR)]},
    {"name": "term$ebnf$1$subexpression$1$ebnf$1", "symbols": ["term$ebnf$1$subexpression$1$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "term$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "term$ebnf$1$subexpression$1$ebnf$2", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "term$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "term$ebnf$1$subexpression$1", "symbols": ["term$ebnf$1$subexpression$1$ebnf$1", "term$ebnf$1$subexpression$1$ebnf$2", "level4"]},
    {"name": "term$ebnf$1", "symbols": ["term$ebnf$1", "term$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "term", "symbols": ["level4", "term$ebnf$1"]},
    {"name": "factor$ebnf$1$subexpression$1$ebnf$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "factor$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "factor$ebnf$1$subexpression$1$ebnf$2", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "factor$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "factor$ebnf$1$subexpression$1", "symbols": [(lexer.has("_EXPONENTIATION") ? {type: "_EXPONENTIATION"} : _EXPONENTIATION), "factor$ebnf$1$subexpression$1$ebnf$1", "expression", "factor$ebnf$1$subexpression$1$ebnf$2", (lexer.has("_EXPONENTIATION") ? {type: "_EXPONENTIATION"} : _EXPONENTIATION)]},
    {"name": "factor$ebnf$1", "symbols": ["factor$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "factor$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "factor", "symbols": ["level5", "factor$ebnf$1"]},
    {"name": "limit$ebnf$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "limit$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "limit$ebnf$2", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "limit$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "limit$ebnf$3", "symbols": [(lexer.has("SIGN") ? {type: "SIGN"} : SIGN)], "postprocess": id},
    {"name": "limit$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "limit$ebnf$4$subexpression$1$ebnf$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "limit$ebnf$4$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "limit$ebnf$4$subexpression$1$ebnf$2", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "limit$ebnf$4$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "limit$ebnf$4$subexpression$1", "symbols": [(lexer.has("_EXPONENTIATION") ? {type: "_EXPONENTIATION"} : _EXPONENTIATION), "limit$ebnf$4$subexpression$1$ebnf$1", "expression", "limit$ebnf$4$subexpression$1$ebnf$2", (lexer.has("_EXPONENTIATION") ? {type: "_EXPONENTIATION"} : _EXPONENTIATION)]},
    {"name": "limit$ebnf$4", "symbols": ["limit$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "limit$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "limit", "symbols": [(lexer.has("_LIM") ? {type: "_LIM"} : _LIM), (lexer.has("_S") ? {type: "_S"} : _S), "variable", "limit$ebnf$1", (lexer.has("_TO") ? {type: "_TO"} : _TO), "limit$ebnf$2", "expression", "limit$ebnf$3", (lexer.has("_S") ? {type: "_S"} : _S), (lexer.has("_OF") ? {type: "_OF"} : _OF), (lexer.has("_S") ? {type: "_S"} : _S), "nest", "limit$ebnf$4"]},
    {"name": "variable", "symbols": [(lexer.has("IDENTIFIER") ? {type: "IDENTIFIER"} : IDENTIFIER)]},
    {"name": "infinite", "symbols": [(lexer.has("_INF") ? {type: "_INF"} : _INF)]},
    {"name": "nest$ebnf$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "nest$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "nest$ebnf$2", "symbols": ["expression"], "postprocess": id},
    {"name": "nest$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "nest$ebnf$3", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "nest$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "nest", "symbols": [(lexer.has("_OPEN") ? {type: "_OPEN"} : _OPEN), "nest$ebnf$1", "nest$ebnf$2", "nest$ebnf$3", (lexer.has("_CLOSE") ? {type: "_CLOSE"} : _CLOSE)]},
    {"name": "tensor$ebnf$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "tensor$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "tensor$ebnf$2$subexpression$1$ebnf$1", "symbols": []},
    {"name": "tensor$ebnf$2$subexpression$1$ebnf$1$subexpression$1$ebnf$1", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "tensor$ebnf$2$subexpression$1$ebnf$1$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "tensor$ebnf$2$subexpression$1$ebnf$1$subexpression$1$ebnf$2", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "tensor$ebnf$2$subexpression$1$ebnf$1$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "tensor$ebnf$2$subexpression$1$ebnf$1$subexpression$1", "symbols": ["tensor$ebnf$2$subexpression$1$ebnf$1$subexpression$1$ebnf$1", (lexer.has("_COMMA") ? {type: "_COMMA"} : _COMMA), "tensor$ebnf$2$subexpression$1$ebnf$1$subexpression$1$ebnf$2", "expression"]},
    {"name": "tensor$ebnf$2$subexpression$1$ebnf$1", "symbols": ["tensor$ebnf$2$subexpression$1$ebnf$1", "tensor$ebnf$2$subexpression$1$ebnf$1$subexpression$1"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "tensor$ebnf$2$subexpression$1$ebnf$2", "symbols": [(lexer.has("_S") ? {type: "_S"} : _S)], "postprocess": id},
    {"name": "tensor$ebnf$2$subexpression$1$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "tensor$ebnf$2$subexpression$1", "symbols": ["expression", "tensor$ebnf$2$subexpression$1$ebnf$1", "tensor$ebnf$2$subexpression$1$ebnf$2"]},
    {"name": "tensor$ebnf$2", "symbols": ["tensor$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "tensor$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "tensor", "symbols": [(lexer.has("_ENTER") ? {type: "_ENTER"} : _ENTER), "tensor$ebnf$1", "tensor$ebnf$2", (lexer.has("_EXIT") ? {type: "_EXIT"} : _EXIT)]},
    {"name": "number$ebnf$1$subexpression$1", "symbols": [(lexer.has("_DOT") ? {type: "_DOT"} : _DOT), (lexer.has("NUMBER") ? {type: "NUMBER"} : NUMBER)]},
    {"name": "number$ebnf$1", "symbols": ["number$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "number$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "number", "symbols": [(lexer.has("NUMBER") ? {type: "NUMBER"} : NUMBER), "number$ebnf$1"]},
    {"name": "level1$subexpression$1", "symbols": ["declaration"]},
    {"name": "level1$subexpression$1", "symbols": ["definition"]},
    {"name": "level1$subexpression$1", "symbols": ["annotation"]},
    {"name": "level1$subexpression$1", "symbols": ["node"]},
    {"name": "level1$subexpression$1", "symbols": ["equation"]},
    {"name": "level1$subexpression$1", "symbols": ["comment"]},
    {"name": "level1$subexpression$1", "symbols": ["use"]},
    {"name": "level1", "symbols": ["level1$subexpression$1"]},
    {"name": "level2$subexpression$1", "symbols": ["expression"]},
    {"name": "level2", "symbols": ["level2$subexpression$1"]},
    {"name": "level3$subexpression$1", "symbols": ["term"]},
    {"name": "level3", "symbols": ["level3$subexpression$1"]},
    {"name": "level4$subexpression$1", "symbols": ["factor"]},
    {"name": "level4$subexpression$1", "symbols": ["limit"]},
    {"name": "level4", "symbols": ["level4$subexpression$1"]},
    {"name": "level5$subexpression$1", "symbols": ["variable"]},
    {"name": "level5$subexpression$1", "symbols": ["infinite"]},
    {"name": "level5$subexpression$1", "symbols": ["nest"]},
    {"name": "level5$subexpression$1", "symbols": ["tensor"]},
    {"name": "level5$subexpression$1", "symbols": ["number"]},
    {"name": "level5", "symbols": ["level5$subexpression$1"]}
]
  , ParserStart: "start"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
